[package]
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
name = "png-to-slp"
version = "0.1.0"

[dependencies]
chariot_io_tools = "0.1"
clap = "2.24"
png = "0.7"

[dependencies.chariot_slp]
git = "https://github.com/ChariotEngine/Slp.git"
branch = "feature/slp-writing"
